name: Run NBA Bot

on:
  schedule:
    - cron: '30 * * * *'  # runs every hour at HH:30
  workflow_dispatch:

jobs:
  run-bot:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.x'
      - name: Install dependencies
        run: pip install requests
      - name: Run bot
        env:
          USERNAME: ${{ secrets.LEMMY_USER }}
          PASSWORD: ${{ secrets.LEMMY_PASS }}
        run: |
          echo "USERNAME = '${{ env.USERNAME }}'" >> bot.py
          echo "PASSWORD = '${{ env.PASSWORD }}'" >> bot.py
          python bot.py
